//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.BMI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BMI.BMISoap")]
    public interface BMISoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  BMICalResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BMICal", ReplyAction="*")]
        WebForm.BMI.BMICalResponse BMICal(WebForm.BMI.BMICalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BMICal", ReplyAction="*")]
        System.Threading.Tasks.Task<WebForm.BMI.BMICalResponse> BMICalAsync(WebForm.BMI.BMICalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BMICalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BMICal", Namespace="http://tempuri.org/", Order=0)]
        public WebForm.BMI.BMICalRequestBody Body;
        
        public BMICalRequest() {
        }
        
        public BMICalRequest(WebForm.BMI.BMICalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BMICalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double Height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double Weigth;
        
        public BMICalRequestBody() {
        }
        
        public BMICalRequestBody(double Height, double Weigth) {
            this.Height = Height;
            this.Weigth = Weigth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BMICalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BMICalResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebForm.BMI.BMICalResponseBody Body;
        
        public BMICalResponse() {
        }
        
        public BMICalResponse(WebForm.BMI.BMICalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BMICalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BMICalResult;
        
        public BMICalResponseBody() {
        }
        
        public BMICalResponseBody(string BMICalResult) {
            this.BMICalResult = BMICalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BMISoapChannel : WebForm.BMI.BMISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BMISoapClient : System.ServiceModel.ClientBase<WebForm.BMI.BMISoap>, WebForm.BMI.BMISoap {
        
        public BMISoapClient() {
        }
        
        public BMISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BMISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BMISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BMISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebForm.BMI.BMICalResponse WebForm.BMI.BMISoap.BMICal(WebForm.BMI.BMICalRequest request) {
            return base.Channel.BMICal(request);
        }
        
        public string BMICal(double Height, double Weigth) {
            WebForm.BMI.BMICalRequest inValue = new WebForm.BMI.BMICalRequest();
            inValue.Body = new WebForm.BMI.BMICalRequestBody();
            inValue.Body.Height = Height;
            inValue.Body.Weigth = Weigth;
            WebForm.BMI.BMICalResponse retVal = ((WebForm.BMI.BMISoap)(this)).BMICal(inValue);
            return retVal.Body.BMICalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebForm.BMI.BMICalResponse> WebForm.BMI.BMISoap.BMICalAsync(WebForm.BMI.BMICalRequest request) {
            return base.Channel.BMICalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebForm.BMI.BMICalResponse> BMICalAsync(double Height, double Weigth) {
            WebForm.BMI.BMICalRequest inValue = new WebForm.BMI.BMICalRequest();
            inValue.Body = new WebForm.BMI.BMICalRequestBody();
            inValue.Body.Height = Height;
            inValue.Body.Weigth = Weigth;
            return ((WebForm.BMI.BMISoap)(this)).BMICalAsync(inValue);
        }
    }
}
